services:
  dhcp-server:
    build:
      context: .
      dockerfile: Dockerfile.dhcp
    image: pxe-dhcp-image:latest
    container_name: pxe-dhcp
    network_mode: host
    restart: "no"
    environment:
      - ENABLE_DNS=false
    cap_add:
      - NET_ADMIN
    volumes:
      - ./scripts/dnsmasq.conf:/etc/dnsmasq.conf:ro
